name: UTRA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://utra.ca" # the base hostname & protocol for your site

# Adds other folders besides _includes, _layouts, _posts
includes:
- html

sass:
    sass_dir: assets/scss
